### ISSUE TITLE
Very big markers on the side, mainly when using flycheck

### ISSUE THREAD

**Issue by ZzAntares** [anler/centered-window-mode#13]
Hello! Thanks for this package from all the solutions I've tried is the one I like the most, however isn't quite there, I'm having an issue when using [`flycheck`](https://github.com/flycheck/flycheck) the error markers expand to be very big that makes them to be visually annoying.

<img width="1518" alt="screen shot 2017-03-25 at 17 02 56" src="https://cloud.githubusercontent.com/assets/3653680/24326839/7bbc7788-117d-11e7-9d0c-1cb2e90e0737.png">

There you can see two errors, and how big they are shown. Is there anything I could try in order to fix this?

Thanks.

**Comment by anler** [comment]
Hi @ZzAntares I've been planning to fix a lot of issues related to the mode and I'll try to take a look at this too. Right know I don't know what's exactly happening in your case or how to fix it.

**Comment by ZzAntares** [comment]
Ok thanks for the answer. For now I've managed to solve this by hiding flycheck errors on the left-fringe using `(setq flycheck-indication-mode nil)`.

Thanks.

**Comment by anler** [comment]
Hi @ZzAntares I've been looking into this and I couldn't find a way of mitigating it (Flycheck uses overlays in the fringe, I can clean them but as soon as you edit the buffer the Flycheck process adds them again) other than using a different theme when using this mode.
