### ISSUE TITLE
Error when enabling centered-window-mode

### ISSUE THREAD

**Issue by lm3m** [anler/centered-window-mode#14]
;; Version: 1.1.0
;; Package-Version: 20170402.355

When I enable centered-window-mode I see the following error:
"Symbol's function definition is void: s-trim"

After that when I do almost any command (include exit emacs) I see the following error:
"Symbol's function definition is void: cwm-center-frame"

**Comment by anler** [comment]
Arrrgh, I forgot to commit the right changes, I pushed a fix.
