### ISSUE TITLE
vertical padding

### ISSUE THREAD

**Issue by mattharrison** [anler/centered-window-mode#2]
It would be really cook to have the ability to specify vertical padding. I often use emacs during presentations where it is useful to keep text off the edges.

**Comment by neeasade** [comment]
necro bump, is this possible in emacs even?

**Comment by anler** [comment]
I remember I was playing with it and was able to get something decent using overlays, but it was too buggy, need to revisit it

**Comment by anler** [comment]
I pushed a new version that adds a small hack that is far from ideal but for my use cases is enough. I updated the README with it.
