### ISSUE TITLE
Customizing certain variables should update window centering

### ISSUE THREAD

**Issue by xiongtx** [anler/centered-window-mode#20]
## Expected behavior

Setting certain customizable variables via Customize should automatically update affected windows.

This can be done using the [`:set`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Definitions.html#Variable-Definitions) keyword in `defcustom`s. The `setfunction` needs to:

- Set variable's value
- Center all windows in all frames

## Actual behavior

Customizing a variable like `cwm-left-fringe-ratio` does not update windows immediately, only after the window is refreshed, e.g. by switching to another buffer.

## Steps to reproduce

Suppose `cwm-left-fringe-ratio` has default value 40 and `centered-window-mode` is on.

1. See that a window `w` is centered with left fringe ratio 40
2. Eval `(customize-set-variable 'cwm-left-fringe-ratio 0)`
3. See that nothing changes
4. Do something to refresh the window, e.g. switch to another buffer and back
5. See that `w` is centered with left fringe ratio 0

## Backtraces if necessary (`M-x toggle-debug-on-error`)

N/A

## Versions of `centered-window-mode`, Emacs, OS etc.

- `centered-window-mode`: `1.2.0`
- Emacs: `GNU Emacs 25.1.50.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by anler** [comment]
@xiongtx are you already working on a fix for this? either way I'll try to take a look during the weekend. Thanks!

**Comment by xiongtx** [comment]
Yes, I'll be taking a look.
