### ISSUE TITLE
Please do not require mac-win

### ISSUE THREAD

**Issue by tarsius** [anler/centered-window-mode#28]
In b6108941dc879fc20696b84f7ee99920d6023671 you added a soft dependency on `mac-win`. This seems unnecessary to me. Recent Emacsen do not contain that library anymore, it was removed when support for "Carbon Emacs" was removed. Also its header used to say that it is automatically loaded by `startup.el` when appropriate. So even if you need that library for backward compatibility, you still don't need to load it explicitly.

I stumbled into this change while automatically extracting dependency information for the Emacsmirror. The tools used to do so currently report this as an unsatisfied dependency.

**Comment by anler** [comment]
Thanks for reporting it @tarsius. What do you think @wyuenho , can we delete that requirement?

**Comment by wyuenho** [comment]
Carbon Emacs still survives [sound and well](https://github.com/railwaycat/homebrew-emacsmacport). It is still being actively developed, packaged and published. Contrary to popular believe, it does not use any Carbon APIs. It merely keeps the old Carbon Emacs default behavior by porting it to Cocoa.

The only reason I `(require 'mac-win nil t)`, was to remove the compilation warnings for `mac-mwheel-scroll` (I guess it's not loaded by `startup.el` anymore). The requirement of this is not even listed in the `Package-Requires` header, so I'm not sure why it will cause problems.

**Comment by wyuenho** [comment]
If I wrap `eval-after-load` over the `require`, would that solve the Emacsmirror problem?

**Comment by tarsius** [comment]
Simply knowing why the feature is being loaded is enough - I can now mark it as needed for "Emacs Mac-port compatibility".

**Comment by anler** [comment]
Thanks both!
