### ISSUE TITLE
Settings customisations - help wanted

### ISSUE THREAD

**Issue by dejmail** [anler/centered-window-mode#30]
Hi there, many thanks for writing this mode! Very useful keeping my head straight.

Apologies if this is a silly question, but how does one actually customise what is specified in this mode ?

I can't seem to get anything to stick in the init.el file, would it possible to add something to the README ?

## Versions of `centered-window-mode`, Emacs, OS etc.

- `centered-window-mode`:
- Emacs: 25.3.2
- OS: Linux, Xubuntu 16.04

**Comment by anler** [comment]
Hi @dejmail no worries, I have updated the README with instructions that should help you to customize the mode. Take a look at [Customization - README](https://github.com/anler/centered-window-mode#customization) and let me know if you need anything else.

**Comment by dejmail** [comment]
Perfect, I felt silly asking but just could get it right.

**Comment by anler** [comment]
There's no silly question! 😉
