### ISSUE TITLE
Centered-Window-Mode for terminal

### ISSUE THREAD

**Issue by blairdrummond** [anler/centered-window-mode#5]
Hey, I wrote something based loosely on your code that does more or less the same thing but works in terminal. It doesn't use fringes, so it doesn't let you alter the colours in the same way, but what can you do. Also, it supports horizontally split centered windows. It could use some better documentation and renaming, but I thought that you might be interested.

[This](https://github.com/blairdrummond/centering-window-mode.git) is the code

[This](http://alexkehayias.tumblr.com/post/98888273308/simple-centered-text-mode-in-emacs) is where I got the premise

**Comment by anler** [comment]
Oh great! I'll take a look asap. Thank you!
