### ISSUE TITLE
I had to make a custom version, here is what it looks like

### ISSUE THREAD

**Issue by mickael-kerjean** [anler/centered-window-mode#7]
Hello,

I love you plugin! 
I just made a few change:
- Fix a bug when the window is less than 110 characters as the margin currently still apply
- Add a new variable so that I can change the text width in my .emacs file
- Enable the plugin as soon as there is some room to display the text

Here is the [code](https://gist.github.com/mickael-kerjean/0d7b5ff8370d4d21867d)

**Comment by anler** [comment]
Thanks a lot @mickael-kerjean ! Are you willing to create a pull request with those changes?

**Comment by mickael-kerjean** [comment]
Sure, I'll use it a bit more this week to ensure everything work fine and will send you the update by the end of the week.

**Comment by anler** [comment]
Sounds great, thanks a lot for the help! :+1:
