### ISSUE TITLE
exclude in some buffers?

### ISSUE THREAD

**Issue by mclearc** [anler/centered-window-mode#9]
Is there a way to keep centered-window-mode from activating in certain buffers? For example, I use  [which-key](https://github.com/justbur/emacs-which-key), and it would be great if, when using centered-window-mode, I could open which key without CWM also being activated there.

**Comment by anler** [comment]
Hi @mclearc at the moment there's no way but I'm going to try to work on it, it's sure a good feature to have :haircut:

**Comment by anler** [comment]
Hi @mclearc I began working on this feature + some other changes, take a look at it [here](https://github.com/anler/centered-window-mode/blob/customize/centered-window-mode.el#L56) Does that system for ignoring buffers suit to you?

**Comment by mclearc** [comment]
Thanks for moving so quickly on this. I'm a bit confused as to how the custom setting is supposed to work though (sorry -- I'm not terribly adept at elisp).

**Comment by anler** [comment]
No prob, I'm not  an expert either. There's this variable `cwm-ignore-buffer-predicates` which is a list of predicate functions (they return t or nil), those functions receive a buffer and return whether or not *ignore* that buffer. By default there's only one function in that list `'cwm/special-buffer-p` that returns `nil` if the buffer's name starts by an asterisk but it's not the `*scratch*` buffer.
If that configuration suits to you, you have to do nothing, if there are some other buffers you want to ignore, you should create a function that tells whether or not ignore that buffer and append it to `cwm-ignore-buffer-predicates`, if you want to completely ignore the default and use just a function of yours to tell which buffers to ignore, just set `cwm-ignore-buffer-predicates` to a list containing your function.
Is it more clear now? I can provide some examples if you need those.

**Comment by mclearc** [comment]
That sounds good. I guess I'm still a little fuzzy on how this would work for which-key (for example), but if you don't have time, no worries, I'll figure it out.

**Comment by anler** [comment]
I did a test, modified something, and now it's working without requiring any work from you. As soon as I merge it into master you can use it.

![cwm](https://cloud.githubusercontent.com/assets/83847/12884720/787b7814-ce60-11e5-8d1a-bfc9fbd16e17.png)

**Comment by mclearc** [comment]
Great - thanks very much!

**Comment by anler** [comment]
Change is merged, it should be mirrored in melpa in a few hours, let me know if there's something wrong. Thank you!
